import img from '../Images/MIUGames_5.jpg'

export const gamesData = [
    {
        id: 1,
        name: "Game 1",
        description: "Exciting adventure game with thrilling missions.Exciting adventure game with thrilling missions.Exciting adventure game with thrilling missions.Exciting adventure game with thrilling missions.Exciting adventure game with thrilling missions.Exciting adventure game with thrilling missions.",
        descriptionTr: "Heyecan verici görevlerle dolu heyecan verici macera oyunu.Heyecan verici görevlerle dolu heyecan verici macera oyunu.Heyecan verici görevlerle dolu heyecan verici macera oyunu.Heyecan verici görevlerle dolu heyecan verici macera oyunu.Heyecan verici görevlerle dolu heyecan verici macera oyunu.Heyecan verici görevlerle dolu heyecan verici macera oyunu",
        descriptionShort: "Exciting adventure game with thrilling missions.",
        descriptionShortTr: "Heyecan verici görevlerle dolu heyecan verici macera oyunu.",
        image: img,
        playLink: "https://play.google.com/store/apps/details?id=game1",
        buttonEng: "Learn More",
        buttonTr: "Daha Fazla Bilgi",
        routeToPage: "/game/1",
        routeToPageTr: "/gametr/1",
    },
    {
        id: 2,
        name: "Game 2",
        description: "Fast-paced racing game with amazing graphics.Fast-paced racing game with amazing graphics.Fast-paced racing game with amazing graphics.Fast-paced racing game with amazing graphics.Fast-paced racing game with amazing graphics.",
        descriptionTr: "Muhteşem grafiklere sahip hızlı yarış oyunu.Muhteşem grafiklere sahip hızlı yarış oyunu..Muhteşem grafiklere sahip hızlı yarış oyunu..Muhteşem grafiklere sahip hızlı yarış oyunu..Muhteşem grafiklere sahip hızlı yarış oyunu.",
        descriptionShort: "Fast-paced racing game with amazing graphics.",
        descriptionShortTr: "Muhteşem grafiklere sahip hızlı yarış oyunu.",
        image: img,
        playLink: "https://play.google.com/store/apps/details?id=game2",
        buttonEng: "Learn More",
        buttonTr: "Daha Fazla Bilgi",
        routeToPage: "/game/2",
        routeToPageTr: "/gametr/2",
    },
    {
        id: 3,
        name: "Game 3",
        description: "Solve challenging puzzles in this brain teaser.Solve challenging puzzles in this brain teaser.Solve challenging puzzles in this brain teaser..Solve challenging puzzles in this brain teaser..Solve challenging puzzles in this brain teaser.",
        descriptionTr: "Bu zeka oyununda zorlu bulmacaları çözün.Bu zeka oyununda zorlu bulmacaları çözün.Bu zeka oyununda zorlu bulmacaları çözün.Bu zeka oyununda zorlu bulmacaları çözün.Bu zeka oyununda zorlu bulmacaları çözün.",
        descriptionShort: "Solve challenging puzzles in this brain teaser.",
        descriptionShortTr: "Bu zeka oyununda zorlu bulmacaları çözün.",
        image: img,
        playLink: "https://play.google.com/store/apps/details?id=game3",
        buttonEng: "Learn More",
        buttonTr: "Daha Fazla Bilgi",
        routeToPage: "/game/3",
        routeToPageTr: "/gametr/3",
    },
    {
        id: 4,
        name: "Game 4",
        description: "Action-packed shooter with multiplayer mode.Action-packed shooter with multiplayer mode.Action-packed shooter with multiplayer mode.Action-packed shooter with multiplayer mode.Action-packed shooter with multiplayer mode.",
        descriptionTr: "Çok oyunculu modlu, aksiyon dolu nişancı oyunu.Çok oyunculu modlu, aksiyon dolu nişancı oyunu.Çok oyunculu modlu, aksiyon dolu nişancı oyunu.Çok oyunculu modlu, aksiyon dolu nişancı oyunu.Çok oyunculu modlu, aksiyon dolu nişancı oyunu.",
        descriptionShort: "Action-packed shooter with multiplayer mode.",
        descriptionShortTr: "Çok oyunculu modlu, aksiyon dolu nişancı oyunu.",
        image: img,
        playLink: "https://play.google.com/store/apps/details?id=game4",
        buttonEng: "Learn More",
        buttonTr: "Daha Fazla Bilgi",
        routeToPage: "/game/4",
        routeToPageTr: "/gametr/4",
    },
    {
        id: 5,
        name: "Game 5",
        description: "A strategic RPG with deep character progression.A strategic RPG with deep character progression.A strategic RPG with deep character progression.A strategic RPG with deep character progression.A strategic RPG with deep character progression.",
        descriptionTr: "Derin karakter gelişimine sahip stratejik bir RPG.Derin karakter gelişimine sahip stratejik bir RPG.Derin karakter gelişimine sahip stratejik bir RPG.Derin karakter gelişimine sahip stratejik bir RPG.Derin karakter gelişimine sahip stratejik bir RPG.",
        descriptionShort: "A strategic RPG with deep character progression.",
        descriptionShortTr: "Derin karakter gelişimine sahip stratejik bir RPG.",
        image: img,
        playLink: "https://play.google.com/store/apps/details?id=game5",
        buttonEng: "Learn More",
        buttonTr: "Daha Fazla Bilgi",
        routeToPage: "/game/5",
        routeToPageTr: "/gametr/5",
    },
    {
        id: 6,
        name: "Game 6",
        description: "Relaxing puzzle game with stunning visuals.Relaxing puzzle game with stunning visuals.Relaxing puzzle game with stunning visuals.Relaxing puzzle game with stunning visuals.Relaxing puzzle game with stunning visuals.",
        descriptionTr: "Çarpıcı görsellere sahip rahatlatıcı bir bulmaca oyunu.Çarpıcı görsellere sahip rahatlatıcı bir bulmaca oyunu.Çarpıcı görsellere sahip rahatlatıcı bir bulmaca oyunu.Çarpıcı görsellere sahip rahatlatıcı bir bulmaca oyunu.Çarpıcı görsellere sahip rahatlatıcı bir bulmaca oyunu.",
        descriptionShort: "Relaxing puzzle game with stunning visuals.",
        descriptionShortTr: "Çarpıcı görsellere sahip rahatlatıcı bir bulmaca oyunu.",
        image: img,
        playLink: "https://play.google.com/store/apps/details?id=game6",
        buttonEng: "Learn More",
        buttonTr: "Daha Fazla Bilgi",
        routeToPage: "/game/6",
        routeToPageTr: "/gametr/6",
    },
];
